version: "3"
services:
    db:
        image: arangodb:3.7.1
        ports:
            -  8529:8529
        environment:
            ARANGO_ROOT_PASSWORD: alox
        volumes:
            -  ./dev/var/db:/var/lib/arangodb3
    runner:
        image: alox:dev-debug
        depends_on:
            -  db
        ports:
            -  42080:80
            -  42443:443
        volumes:
            -  ./dev/etc:/etc/alox
            -  ./dev/var:/var/alox