storage_dir = "./test-data/var"
conf_dir = "./test-data/conf.d"

[api]
host = "localhost"
port = "1337"
prefix = "/api"

[arango]
url = "http://localhost:8529"
username = "alox"
password = "alox"
db = "alox"