[package]
name = "alox"
version = "0.1.0"
authors = ["Daniel Wanner <daniel.wanner@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tide = "0.13.0"

[dependencies.async-std]
version = "1.6.3"
features = [ "unstable", "attributes" ]
